# Generated by Django 2.1.3 on 2019-01-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('ipo_year', models.CharField(max_length=10)),
                ('sector', models.CharField(max_length=55)),
                ('industry', models.CharField(max_length=55)),
            ],
        ),
    ]
