# Generated by Django 2.1.3 on 2019-01-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktrendsbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRepliedTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.IntegerField()),
            ],
        ),
    ]
