# Generated by Django 2.1.3 on 2019-01-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktrendsbot', '0002_postrepliedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name_has_been_formatted',
            field=models.BooleanField(default=False),
        ),
    ]
