# Generated by Django 2.1.3 on 2019-01-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktrendsbot', '0003_company_name_has_been_formatted'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrepliedto',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
