# Generated by Django 2.1.3 on 2019-01-06 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocktrendsbot', '0004_postrepliedto_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postrepliedto',
            name='url',
        ),
    ]
