# Generated by Django 2.1.3 on 2019-01-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktrendsbot', '0005_remove_postrepliedto_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrepliedto',
            name='submission_id',
            field=models.CharField(max_length=55),
        ),
    ]
