# Generated by Django 2.1.3 on 2019-01-18 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocktrendsbot', '0008_isrunning'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IsRunning',
        ),
    ]
