# Generated by Django 2.1.3 on 2019-01-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('candidate_id', models.CharField(blank=True, max_length=255)),
                ('candidate_status', models.CharField(blank=True, max_length=5)),
                ('district', models.CharField(blank=True, max_length=2)),
                ('first_file_date', models.DateField(blank=True, null=True)),
                ('incumbent_challenge_full', models.CharField(blank=True, max_length=55, null=True)),
                ('last_f2_date', models.DateField(blank=True, null=True)),
                ('last_file_date', models.DateField(blank=True, null=True)),
                ('load_date', models.DateField(blank=True, null=True)),
                ('office_full', models.CharField(blank=True, max_length=9, null=True)),
                ('party_full', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=2)),
            ],
        ),
    ]
