# Generated by Django 2.1.3 on 2019-01-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fec', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='party_full',
            new_name='party',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='first_file_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='incumbent_challenge_full',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='last_f2_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='last_file_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='load_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='office_full',
        ),
        migrations.AddField(
            model_name='candidate',
            name='incumbent_challenge_status',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
